### ISSUE TITLE
V4Decrypt Missing?

### ISSUE THREAD

**Issue by koufopoulosf** [aidantwoods/go-paseto#28]
Hello,

May I please ask you why the V4Decrypt is missing from the package? Specifically the local version.

I have some issues with finding it.

I would really appreciate your support on that.

Thank you very much for your valuable time.

Best Regards,

Filippos

**Comment by aidantwoods** [comment]
Hello!

The function you're looking for is named `ParseV4Local` on a parser instance 🙂 

The parser is responsible for both decryption and validating the token against any loaded rules as an atomic operation (this is a design decision to guide against accidental use of a decrypted token before rules/claims have also been checked, like token expiry).

**Comment by koufopoulosf** [comment]
Hello,

Thank you very much for your reply!

I would highly appreciate it, if you could provide me a working example using the ParseV4Local🙏.

Thank you very much once again!

Best Regards,

Filippos

**Comment by aidantwoods** [comment]
Here's an example from the tests 🙂 

https://github.com/aidantwoods/go-paseto/blob/48bba7745dc963273b2a95e1b96064ef9a6d7a15/claims_test.go#L106

The non error returned value there is the parsed, decrypted, and validated token. For the local mode, make sure to use the same key (and implicit string if used) as was used to create the token.

**Comment by koufopoulosf** [comment]
Thank you very much for your reply once again!

Is there any chance that you are available for freelancing to review a code for user auth with pasetoV4 I am making with a friend?

Thank you🙏

**Comment by koufopoulosf** [comment]
Also let me note that the hyperlink on the README.md isn't working:

Paseto is everything you love about JOSE (JWT, JWE, JWS) without any of the [many design deficits that plague the JOSE standards](https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid).

**Comment by koufopoulosf** [comment]
Now the hyperlink is working. Thank you very much for your valuable help! Be well :)
