### ISSUE TITLE
Update Test Vectors

### ISSUE THREAD

**Issue by scottarc** [aidantwoods/go-paseto#4]
The latest test vectors include "expected fail" test cases. https://github.com/paseto-standard/test-vectors

**Comment by aidantwoods** [comment]
Thanks for this! I have this as a pipeline step, but maybe it should be a cron 😆 

https://github.com/aidantwoods/go-paseto/runs/6867807360?check_suite_focus=true

**Comment by aidantwoods** [comment]
No code changes necessary to catch those expect fails, so no need to do a re-release for this one I think.
