### ISSUE TITLE
Generating key from existing ED25519 keypair is confusing

### ISSUE THREAD

**Issue by jcfvalente** [aidantwoods/go-paseto#40]
If you want to generate an ED25519 key locally and then use that key with the lib, the process is slightly confusing. So far the only way that I was able to do it was doing this:

```
	file, err := os.ReadFile("/path/to/file")
	if err != nil {
		return nil, err
	}

	key, err := ssh.ParseRawPrivateKey(file)
	if err != nil {
		log.Fatalf("failed to parse private key: %v", err)
	}

	keyFormat := key.(*ed25519.PrivateKey)

	privateKey, err := paseto.NewV4AsymmetricSecretKeyFromSeed(hex.EncodeToString(keyFormat.Seed()))
	if err != nil {
		return nil, err
	}
```

This might just be my personal perception, but if you are using this for the first time it can be confusing. I think that `NewV4AsymmetricSecretKeyFromBytes` is a also slightly misleading, as at first one might think that you can just feed the raw bytes after reading the file.

To improve the usability of the package, I would suggest either:
- Add helper functions to create the key:
   - Generate a secret key from raw bytes (e.g bytes after reading the file)
   - Generate a secret key from a *ed25519.PrivateKey file
- Add documentation on the README on how to do this

Thank you for your work on this package, I've been experimenting with it and it has been great so far!

**Comment by aidantwoods** [comment]
Thanks, that's good feedback!

I think I'll probably go with writing some constructors to accept the appropriate standard library types for each key, as that seems like the most sensible common currency.

**Comment by aidantwoods** [comment]
#43 Adds some constructors for all the asymmetric key types, from the standard Go objects.
